### ISSUE TITLE
Hacer la request del Podio

### ISSUE THREAD

**Issue by jjg99** [jjg99/ProyectoFinalPAT#6]

**Comment by J0nan** [comment]
¿@jjg99 uso un [accordion](https://getbootstrap.com/docs/5.0/components/accordion/) para el podio? Había pensado en el Flush, y cuando se desglose, aparezca su punctuation y el número de desafíos completados, que te parece?

**Comment by jjg99** [comment]
> ¿@jjg99 uso un [accordion](https://getbootstrap.com/docs/5.0/components/accordion/) para el podio? Había pensado en el Flush, y cuando se desglose, aparezca su punctuation y el número de desafíos completados, que te parece?

Si, me parece bien que hagamos un acordeón flash, y pongamos la información correspondiente

**Comment by J0nan** [comment]
Ya se ha terminado la pestaña de Podio. Cuando se accede a `/podio`, Java hace una lista ordenada de todos los usuarios en función de la posición. Usando dicha lista y la templete de `podio.html` se carga de manera dinámica el podio, usado una [api externa](https://www.countryflags.io/) para obtener las banderas en función del código de país que esta almacenado con cada usuario. Se ha intentado realizar al máximo un diseño liquido.

![image](https://user-images.githubusercontent.com/46595866/113495818-4544cd00-94f4-11eb-9a2a-4f10d8e09e78.png)

![image](https://user-images.githubusercontent.com/46595866/113495885-dc118980-94f4-11eb-8391-a59e657abf54.png)

![image](https://user-images.githubusercontent.com/46595866/113495823-58579d00-94f4-11eb-8508-3aa2e4b2d875.png)
